### ISSUE TITLE
Parameterise 'processing' scripts with locations of input and output files

### ISSUE THREAD

**Issue by Athas** [diku-dk/futhark-benchmark-dashboard#9]
The various scripts in the `processing/` subdirectory currently make assumptions about where to find the Futhark compiler sources (in `../../futhark`) and the unprocessed benchmark results (`./benchmark-results`).  Further, the processed results are always written to a directory `./out`.  While this information is available to the Buildbot master, it is awkward to place it in exactly these relative paths.  It would be better if three environment variables were provided to control these directories.

Even better would be if they were simply command line parameters to the various scripts.  I don't quite get why this processing has been structured as a Makefile, since none of the rules have any dependencies.  This could just be a shell script (or a single Javascript program).

**Comment by fredefl** [comment]
This will be added in: #13 

Currently the _help_ command looks like this:
```

  Usage: index [options] [command]

  Options:

    -V, --version                  output the version number
    --skip-commits                 Skip getting commit information
    --benchmark-results-dir <dir>   (default: ./benchmark-results)
    --out-dir <dir>                 (default: ./out)
    --settings-file <file>          (default: ./settings.json)
    --futhark-git-dir <dir>         (default: ../../futhark)
    -h, --help                     output usage information

  Commands:

    process [options]              process futhark-benchmark data
```

```

  Usage: process [options]

  process futhark-benchmark data

  Options:

    --optimize-threshold <threshold>  Optimization diff threshold (default: 0.02)
    -h, --help                        output usage information
```
